# Bot configuration - this file can be tracked in git and remotely modified
# Environment-specific settings (production vs development) are in environment.yaml

gpio:
  # Add GPIO pin configurations here as needed
  led_pin: 18
  sensor_pin: 24

# Power monitoring with INA219 sensor
ina219:
  # I2C address (can be 0x40, 0x41, 0x44, 0x45)
  i2c_address: 0x40
  # Measurement interval in seconds
  measurement_interval: 1.0
  # Enable logging of measurements
  log_measurements: true
  # Power thresholds for alerts (in watts)
  low_power_threshold: 0.5
  high_power_threshold: 10.0

# Other configuration options
debug: true
log_level: "DEBUG"
colorized_logging: true
