# Bot configuration - this file can be tracked in git and remotely modified
# Environment-specific settings (production vs development) are in environment.yaml

# Runner configurations
runners:
  # Solar power monitoring INA219
  solar_power:
    type: ina219
    label: "Solar Power Monitor"
    enabled: true
    i2c_address: 0x40
    measurement_interval: 1.0
    log_measurements: true
    low_power_threshold: 0.5
    high_power_threshold: 10.0

  # Docked power monitoring INA219
  docked_power:
    type: ina219
    label: "Docked Power Monitor"
    enabled: false
    i2c_address: 0x41
    measurement_interval: 1.0
    log_measurements: true
    low_power_threshold: 0.5
    high_power_threshold: 15.0

# Main application configuration
application:
  # Enable/disable threaded runner system
  threaded_runners: true
  # Main loop interval in seconds
  main_loop_interval: 2
  # Graceful shutdown timeout in seconds
  shutdown_timeout: 5.0

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "DEBUG"
  # Enable colorized logging output
  colorized: true
  # Enable debug mode
  debug: true
  # Individual color settings for each log level
  colors:
    DEBUG: "blue"
    INFO: "white"
    WARNING: "yellow"
    ERROR: "red"
    CRITICAL: "red,bg_yellow"
  # Log format settings
  format:
    # Date format for timestamps
    date_format: "%Y-%m-%d %H:%M:%S"
    # Message format (with color placeholders)
    message_format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    # Simple format (without colors)
    simple_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
