# Bot configuration - this file can be tracked in git and remotely modified
# Environment-specific settings (production vs development) are in environment.yaml

# Runner configurations
runners:
  # Solar power monitoring INA219
  solar_power:
    type: ina219
    label: "Solar Power Monitor"
    enabled: true
    i2c_address: 0x40
    measurement_interval: 1.0
    log_measurements: true
    low_power_threshold: 0.5
    high_power_threshold: 10.0

  # Docked power monitoring INA219
  docked_power:
    type: ina219
    label: "Docked Power Monitor"
    enabled: false
    i2c_address: 0x41
    measurement_interval: 1.0
    log_measurements: true
    low_power_threshold: 0.5
    high_power_threshold: 15.0

  # PiPower UPS monitoring
  pipower:
    type: pipower
    label: "PiPower UPS Monitor"
    enabled: true
    measurement_interval: 1.0
    log_readings: true
    # GPIO pin configuration (BCM numbering)
    bt_lv_pin: 17 # Battery voltage pin (requires ADC)
    adc_channel: 0 # ADC channel for BT_LV (e.g., MCP3008 channel)
    in_dt_pin: 18 # USB power input detect
    chg_pin: 27 # Charging status
    lo_dt_pin: 22 # Low battery detect
    # Alert thresholds (consecutive readings)
    low_battery_alert_threshold: 3
    no_usb_alert_threshold: 3

# Main application configuration
application:
  # Enable/disable threaded runner system
  threaded_runners: true
  # Main loop interval in seconds
  main_loop_interval: 2
  # Graceful shutdown timeout in seconds
  shutdown_timeout: 5.0
  # Battery safety configuration
  battery_safety:
    # Minimum battery percentage before forcing return to dock
    min_battery_threshold: 20.0
    # Maximum allowed distance from dock as a factor of remaining battery
    # e.g. 0.5 means at 50% battery, max distance is 25% of total range
    max_distance_factor: 0.5
    # How often to update battery level in the behavior tree (seconds)
    update_interval: 1.0

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "DEBUG"
  # Enable colorized logging output
  colorized: true
  # Enable debug mode
  debug: true
  # Individual color settings for each log level
  colors:
    DEBUG: "blue"
    INFO: "white"
    WARNING: "yellow"
    ERROR: "red"
    CRITICAL: "red,bg_yellow"
  # Log format settings
  format:
    # Date format for timestamps
    date_format: "%Y-%m-%d %H:%M:%S"
    # Message format (with color placeholders)
    message_format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    # Simple format (without colors)
    simple_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
